name: 'CXM IAC Crawler'
description: 'Scan Terraform infrastructure and send resources to CXM API'
branding:
  icon: 'cloud'
  color: 'blue'

inputs:
  skip-checkout:
    description: 'Skip the checkout step (use if you have already checked out the repository)'
    required: false
    default: 'false'
  path:
    description: 'Specific Terraform entrypoint path(s) to scan (comma-separated). If provided, lock file discovery is skipped.'
    required: false
    default: ''
  cxm-api-key:
    description: 'CXM API key for authentication'
    required: true
  cxm-api-endpoint:
    description: 'CXM API endpoint URL'
    required: false
  terraform-show-timeout:
    description: 'Timeout in seconds for terraform show command (default: 300)'
    required: false
    default: '300'
  sensitive-fields:
    description: 'Comma-separated list of additional sensitive field patterns to redact'
    required: false
    default: ''
  max-retries:
    description: 'Maximum number of retry attempts for API calls (default: 3)'
    required: false
    default: '3'
  timeout-seconds:
    description: 'Timeout in seconds for API calls (default: 30)'
    required: false
    default: '30'
  verbose:
    description: 'Enable verbose logging'
    required: false
    default: 'false'
  repository-url:
    description: 'Repository URL to include in API requests (defaults to current repository URL)'
    required: false
    default: ${{ github.repositoryUrl }}
  dry-run:
    description: 'Enable dry-run mode (parse data without posting to API)'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: 'latest'

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_wrapper: false

    - name: Install IAC Crawler
      shell: bash
      run: |
        cd "${{ github.action_path }}"
        uv pip install --system .

    - name: Run IAC Crawler
      shell: bash
      env:
        TERRAFORM_SHOW_TIMEOUT: ${{ inputs.terraform-show-timeout }}
        SENSITIVE_FIELDS: ${{ inputs.sensitive-fields }}
        CXM_MAX_RETRIES: ${{ inputs.max-retries }}
        CXM_TIMEOUT_SECONDS: ${{ inputs.timeout-seconds }}
      run: |
        VERBOSE_FLAG=""
        if [ "${{ inputs.verbose }}" = "true" ]; then
          VERBOSE_FLAG="--verbose"
        fi

        DRY_RUN_FLAG=""
        if [ "${{ inputs.dry-run }}" = "true" ]; then
          DRY_RUN_FLAG="--dry-run"
        fi

        if [ -n "${{ inputs.path }}" ]; then
          echo "Scanning specific path(s): ${{ inputs.path }}"
          cxm-iac-crawler $VERBOSE_FLAG $DRY_RUN_FLAG --path "${{ inputs.path }}" --repository-url "${{ inputs.repository-url }}" "${{ github.workspace }}"
        else
          echo "Scanning repository: ${{ github.workspace }}"
          cxm-iac-crawler $VERBOSE_FLAG $DRY_RUN_FLAG --repository-url "${{ inputs.repository-url }}" "${{ github.workspace }}"
        fi
